name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Dockerfile'
      - 'requirements.txt'
      - 'callbacks/**'
      - 'assets/**'
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository|lower }}/photo-gallery

permissions:  # 新增权限控制
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 从v2升级到v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # 从v1升级到v3
      with:
        driver: docker-container
        install: true  # 新增安装参数

    - name: Cache Docker layers
      uses: actions/cache@v3  # 从v2升级到v3
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/requirements.txt') }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-docker-${{ hashFiles('**/requirements.txt') }}-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3  # 从v1升级到v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/${{ github.repository|lower }}/photo-gallery:main
          ghcr.io/${{ github.repository|lower }}/photo-gallery:sha-${{ github.sha }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false  # 新增安全特性
        sbom: false